Boots togglegoggle
Jackarunda/gmod pull request #156
Opened 2022-09-06 03:09 UTC by AdventureBootCoder

Code, and request are by SpiffyJUNIOR.
Seems to work just fin for me.

2022-09-08 00:33 UTC, SpiffyJUNIOR commented
no need for the eyes check, that slot is meant for eyewear lmao. just do:
```
concommand.Add("jmod_ez_togglegoggles",function()
	local ply=LocalPlayer()
	if not((IsValid(ply))and(ply:Alive()))then return end
	local ItemID,ItemData,ItemInfo=GetItemInSlot(ply.EZarmor,"eyes")
	if not(ItemID)then return end
	if (ItemID) then
		net.Start("JMod_Inventory")
		net.WriteInt(2,8) -- toggle
		net.WriteString(ItemID)
		net.SendToServer()
	end
end)

2022-10-02 22:52 UTC, Jackarunda approved these changes

2022-10-02 22:54 UTC, Jackarunda requested changes
hol up

2022-10-02 23:10 UTC, Jackarunda approved these changes

2022-10-02 23:11 UTC, merged